"""
backend/verifier.py

Verifies the new, detailed wipe certificates generated by Destroyer.
Supports:
- JSON certificates (new structure)
- QR code certificates (verifying the log hash)
"""

import json
import os
from pathlib import Path
from typing import Dict

from PIL import Image
from pyzbar.pyzbar import decode


def verify_certificate(cert_path: str) -> Dict:
    """
    Verify a detailed wipe certificate.
    - cert_path: path to certificate.json
    Returns: dict {valid: bool, error: str, data: dict}
    """
    if not os.path.exists(cert_path):
        return {"valid": False, "error": "Certificate file not found", "data": None}

    try:
        with open(cert_path, "r") as f:
            data = json.load(f)

        # <<< CHANGED: Update the required fields to match the new certificate format >>>
        required = ["certificate_id", "timestamp_utc", "status", "wipe_mode", "device_details", "verification"]
        for field in required:
            if field not in data:
                return {"valid": False, "error": f"Missing top-level field: {field}", "data": data}

        # <<< NEW: Add a check for nested fields to be more thorough >>>
        if "path" not in data["device_details"]:
            return {"valid": False, "error": "Missing 'path' in device_details", "data": data}
        if "log_hash_sha256" not in data["verification"]:
            return {"valid": False, "error": "Missing 'log_hash_sha256' in verification", "data": data}

        return {"valid": True, "error": "", "data": data}

    except Exception as e:
        return {"valid": False, "error": f"JSON parsing error: {e}", "data": None}


def verify_qr(qr_path: str) -> Dict:
    """
    Verify wipe certificate from a QR code.
    The QR now contains a small JSON payload with the cert ID and hash.
    Returns: dict {valid: bool, error: str, data: dict}
    """
    if not Path(qr_path).exists():
        return {"valid": False, "error": "QR file not found", "data": None}

    try:
        img = Image.open(qr_path)
        decoded = decode(img)
        if not decoded:
            return {"valid": False, "error": "No QR code found in image", "data": None}

        qr_data = decoded[0].data.decode("utf-8")
        cert_data = json.loads(qr_data)

        # <<< CHANGED: The QR now only contains ID and hash for quick verification >>>
        required = ["certificate_id", "log_hash"]
        for field in required:
            if field not in cert_data:
                return {"valid": False, "error": f"QR is invalid, missing field: {field}", "data": cert_data}

        # The QR is considered valid if it's readable and has the correct fields.
        # The next step would be to compare its hash to the one in the JSON file.
        return {"valid": True, "error": "", "data": cert_data}

    except Exception as e:
        return {"valid": False, "error": f"QR reading error: {e}", "data": None}
